version: "3"
services:
  n2n_supernode:
    build:
      context: .
      dockerfile: Dockerfile
    image: zctmdc/n2n_ntop
    container_name: n2n_supernode
    restart: always
    privileged: true
    ports:
      - 10090:10090/udp
    environment:
      - MODE=SUPERNODE
      - SUPERNODE_PORT=10090
      - N2N_ARGS=-v

  n2n_edge_dhcpd:
    depends_on:
      n2n_supernode:
        condition: service_healthy
    image: zctmdc/n2n_ntop
    container_name: n2n_edge_dhcpd
    restart: always
    privileged: true
    # network_mode: host
    environment:
      - MODE=DHCPD
      - SUPERNODE_HOST=n2n_supernode
      - SUPERNODE_PORT=10090
      - EDGE_TUN=edge_dhcpd
      - EDGE_IP=10.31.32.1
      - EDGE_COMMUNITY=n2n
      - EDGE_KEY=test
      - EDGE_ENCRYPTION=A3
    # volumes:
    #   - ./config/dhcpd.conf:/etc/dhcp/dhcpd.conf:ro
    links:
      - n2n_supernode

  n2n_edge_dhcpc:
    depends_on:
      n2n_edge_dhcpd:
        condition: service_healthy
    image: zctmdc/n2n_ntop
    container_name: n2n_edge_dhcpc
    restart: always
    privileged: true
    # network_mode: host
    environment:
      - MODE=DHCPC
      - SUPERNODE_HOST=n2n_supernode
      - SUPERNODE_PORT=10090
      - EDGE_TUN=edge_dhcpc
      - EDGE_COMMUNITY=n2n
      - EDGE_KEY=test
      - EDGE_ENCRYPTION=A3
    links:
      - n2n_supernode

  n2n_edge_static:
    depends_on:
      n2n_supernode:
        condition: service_healthy
    image: zctmdc/n2n_ntop
    container_name: n2n_edge_static
    restart: always
    privileged: true
    # network_mode: host
    environment:
      - MODE=STATIC
      - SUPERNODE_HOST=n2n_supernode
      - SUPERNODE_PORT=10090
      - EDGE_TUN=edge_static
      - EDGE_IP=10.31.32.10
      - EDGE_COMMUNITY=n2n
      - EDGE_KEY=test
      - EDGE_ENCRYPTION=A3
    links:
      - n2n_supernode
