version: "3"
services:
  test-n2n_supernode:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: zctmdc/n2n_ntop
    container_name: test_n2n_supernode
    restart: always
    privileged: true
    environment:
      - MODE=SUPERNODE
      - SUPERNODE_PORT=10090

  test-n2n_edge_dhcpd:
    depends_on:
      - test-n2n_supernode
    image: zctmdc/n2n_ntop
    container_name: test_n2n_edge_dhcpd
    restart: always
    privileged: true
    # network_mode: host
    environment:
      - MODE=DHCPD
      - SUPERNODE_HOST=test-n2n_supernode
      - SUPERNODE_PORT=10090
      - EDGE_TUN=test_edge_dhcpd
      - EDGE_IP=10.10.10.1
      - EDGE_COMMUNITY=n2n
      - EDGE_KEY=test
      - EDGE_ENCRYPTION=A3
    # volumes:
    #   - ./config/dhcpd.conf:/etc/dhcp/dhcpd.conf:ro
    links:
      - test-n2n_supernode

  test-n2n_edge_dhcpc:
    depends_on:
      - test-n2n_edge_dhcpd
      - test-n2n_supernode
    image: zctmdc/n2n_ntop
    container_name: test_n2n_edge_dhcpc
    restart: always
    privileged: true
    # network_mode: host
    environment:
      - MODE=DHCPC
      - SUPERNODE_HOST=test-n2n_supernode
      - SUPERNODE_PORT=10090
      - EDGE_TUN=test_edge_dhcpc
      - EDGE_COMMUNITY=n2n
      - EDGE_KEY=test
      - EDGE_ENCRYPTION=A3
    links:
      - test-n2n_supernode

  test-n2n_edge_static:
    depends_on:
      - test-n2n_supernode
    image: zctmdc/n2n_ntop
    container_name: test_n2n_edge_tatic
    restart: always
    privileged: true
    # network_mode: host
    environment:
      - MODE=STATIC
      - SUPERNODE_HOST=test-n2n_supernode
      - SUPERNODE_PORT=10090
      - EDGE_TUN=test_edge_static
      - EDGE_IP=10.10.10.10
      - EDGE_COMMUNITY=n2n
      - EDGE_KEY=test
      - EDGE_ENCRYPTION=A3
    links:
      - test-n2n_supernode

  test-n2n_healthcheck:
    depends_on:
      - test-n2n_edge_dhcpd
      - test-n2n_supernode
    image: zctmdc/n2n_ntop
    container_name: test_n2n_edge_healthcheck
    restart: always
    privileged: true
    # network_mode: host
    environment:
      - MODE=DHCP
      - SUPERNODE_HOST=test-n2n_supernode
      - SUPERNODE_PORT=10090
      - EDGE_TUN=test_edge_healthcheck
      - EDGE_COMMUNITY=n2n
      - EDGE_KEY=test
      - EDGE_ENCRYPTION=A3
    links:
      - test-n2n_supernode
    command:
      [
        "/bin/bash",
        "-c",
        "/usr/local/sbin/run.sh &sleep 2 && /usr/local/sbin/n2n_healthcheck.sh"
      ]
