version: "3"
services:
  n2n_supernode:
    build:
      context: .
      dockerfile: Dockerfile
    image: zctmdc/n2n_ntop:Alpha
    restart: always
    privileged: true
    ports:
      - 10086:10086/udp
    environment:
      - MODE=SUPERNODE
      - SUPERNODE_PORT=10086
      - N2N_ARGS=-f

  n2n_edge_dhcpd:
    depends_on:
      - n2n_supernode
    image: zctmdc/n2n_ntop:Alpha
    restart: always
    privileged: true
    # network_mode: host
    environment:
      - MODE=DHCPD
      - SUPERNODE_HOST=n2n_supernode
      - SUPERNODE_PORT=10086
      - EDGE_TUN=edge_dhcpd
      - EDGE_IP=10.10.10.1
      - EDGE_COMMUNITY=n2n
      - EDGE_KEY=test
      - EDGE_ENCRYPTION=A3
      - N2N_ARGS=-f
    # volumes:
    #   - ./dhcpd.conf:/etc/dhcp/dhcpd.conf:ro
    external_links:
      - n2n_supernode:n2n_supernode

  n2n_edge_dhcp:
    depends_on:
      - n2n_edge_dhcpd
      - n2n_supernode
    image: zctmdc/n2n_ntop:Alpha
    restart: always
    privileged: true
    # network_mode: host
    environment:
      - MODE=DHCP
      - SUPERNODE_HOST=n2n_supernode
      - SUPERNODE_PORT=10086
      - EDGE_TUN=edge_dhcp
      - EDGE_COMMUNITY=n2n
      - EDGE_KEY=test
      - EDGE_ENCRYPTION=A3
      - N2N_ARGS=-f
    external_links:
      - n2n_supernode:n2n_supernode

  n2n_edge_static:
    depends_on:
      - n2n_supernode
    image: zctmdc/n2n_ntop:Alpha
    restart: always
    privileged: true
    # network_mode: host
    environment:
      - MODE=STATIC
      - SUPERNODE_HOST=n2n_supernode
      - SUPERNODE_PORT=10086
      - EDGE_TUN=edge_static
      - EDGE_IP=10.10.10.10
      - EDGE_COMMUNITY=n2n
      - EDGE_KEY=test
      - EDGE_ENCRYPTION=A3
      - N2N_ARGS=-f
    external_links:
      - n2n_supernode:n2n_supernode
