FROM debian:stable-slim as downloader

ARG name="n2n-downloader"
ARG summary="Base build image for n2n built on-top of debian:stable-slim"
LABEL description="${summary}" \
  maintainer="<zctmdc@outlook.com>" \
  app.kubernetes.io/name="${name}" \
  org.opencontainers.image.title="${name}" \
  org.opencontainers.artifact.description="${summary}" \
  org.opencontainers.image.url="https://hub.docker.com/r/zctmdc/n2n" \
  org.opencontainers.image.source="https://github.com/zctmdc/docker/tree/alpha/n2n" \
  org.opencontainers.image.authors="zctmdc@outlook.com" \
  org.opencontainers.image.description="${summary}" \
  org.opencontainers.image.documentation="https://github.com/zctmdc/docker/tree/alpha/n2n/doc/build.md" \
  org.opencontainers.image.licenses="MIT"

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get -qq update
RUN apt-get -qq -y install \
  bash curl wget unzip

# 安装RAR
WORKDIR /tmp/scripts/
COPY ./scripts/build/0x0_init-logger.sh ./scripts/build/2x0_install_rar.sh /tmp/scripts/
RUN chmod +x /tmp/scripts/*.sh
RUN /tmp/scripts/2x0_install_rar.sh

ARG VERSION_BIG
ARG VERSION_SMALL
ARG VERSION_COMMIT
ARG VERSION_B_S_rC
# ARG STR_DOWNLOAD_URLS


COPY ./scripts/build/* /tmp/scripts/
RUN chmod +x /tmp/scripts/*.sh

ARG DOWNLOAD_PATH='/tmp/n2n'

# 下载需要的文件
COPY ./tmp/down_urls.txt /tmp/down_urls.txt
RUN /tmp/scripts/2x3_n2n_down.sh
ARG N2N_DESC_DIR='/tmp/desc'
# 解压，选择最大的edge文件
RUN /tmp/scripts/2x4_n2n_extract_all.sh
RUN /tmp/scripts/2x5_n2n_sel_biggest.sh

FROM ubuntu:20.04

ARG name="n2n"
ARG summary="n2n built on-top of ubuntu:20.04"
LABEL description="${summary}" \
  maintainer="<zctmdc@outlook.com>" \
  app.kubernetes.io/name="${name}" \
  org.opencontainers.image.title="${name}" \
  org.opencontainers.artifact.description="${summary}" \
  org.opencontainers.image.url="https://hub.docker.com/r/zctmdc/n2n" \
  org.opencontainers.image.source="https://github.com/zctmdc/docker/tree/alpha/n2n" \
  org.opencontainers.image.authors="zctmdc@outlook.com" \
  org.opencontainers.image.description="${summary}" \
  org.opencontainers.image.licenses="MIT"

# edge need ifconfig
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get -qq update
RUN apt-get -qq -y install \
  net-tools busybox iptables isc-dhcp-client isc-dhcp-server inetutils-ping 
RUN touch /var/lib/dhcp/dhcpd.leases

WORKDIR /usr/local/sbin/
ARG N2N_DESC_DIR="/tmp/desc"
COPY --from=downloader \
  ${N2N_DESC_DIR}/supernode \
  ${N2N_DESC_DIR}/edge \
  /usr/local/sbin/
RUN ls

WORKDIR /tmp/scripts/
COPY ./scripts/build/*.sh /tmp/scripts/
RUN chmod +x /tmp/scripts/*
RUN /tmp/scripts/3x0_n2n_fixlib.sh
RUN rm -rf /tmp/*

WORKDIR /usr/local/sbin/

ARG VERSION_BIG
ARG VERSION_SMALL
ARG VERSION_COMMIT
ARG VERSION_B_S_rC
ARG STR_DOWNLOAD_URLS

ENV VERSION_BIG=${VERSION_BIG}
ENV VERSION_SMALL=${VERSION_SMALL}
ENV VERSION_COMMIT=${VERSION_COMMIT}
ENV VERSION_B_S_rC=${VERSION_B_S_rC}
ENV STR_DOWNLOAD_URLS=${STR_DOWNLOAD_URLS}
