FROM debian:stable-slim as downloader

ARG name="n2n-downloader"
ARG summary="Base build image for n2n built on-top of debian:stable-slim"
LABEL description="${summary}" \
  maintainer="<zctmdc@outlook.com>" \
  app.kubernetes.io/name="${name}" \
  org.opencontainers.image.title="${name}" \
  org.opencontainers.artifact.description="${summary}" \
  org.opencontainers.image.url="https://hub.docker.com/r/zctmdc/n2n" \
  org.opencontainers.image.source="https://github.com/zctmdc/docker/tree/alpha/n2n" \
  org.opencontainers.image.authors="zctmdc@outlook.com" \
  org.opencontainers.image.description="${summary}" \
  org.opencontainers.image.documentation="https://github.com/zctmdc/docker/tree/alpha/n2n/doc/build.md"\
  org.opencontainers.image.licenses="MIT"

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get -qq update
RUN apt-get -qq -y install \
  bash curl wget unzip

# 安装RAR
WORKDIR /tmp/scripts/
COPY ./scripts/init_logger.sh ./scripts/install_rar.sh /tmp/scripts/
RUN chmod +x /tmp/scripts/*.sh
RUN /tmp/scripts/install_rar.sh

ARG KERNEL=linux
# 用于自定义机型编译,未自动识别时请赋值
ARG MACHINE
ARG BIG_VERSION
ARG SMALL_VERSION
ARG COMMIT
ARG VERSION_B_S_rC
ARG MANUAL_BUILD

# 选择对应版本文件
WORKDIR /tmp/n2n/scripts/
# COPY . /tmp/n2n/
# RUN chmod +x /tmp/n2n/scripts/*.sh
# RUN /tmp/n2n/scripts/build-docker.sh

# RUN mkdir -p /tmp/down/ && cp /tmp/n2n/result/build_src/* /tmp/down/ && ls /tmp/down/

COPY ./result/build_src/ /tmp/down/
COPY ./scripts/ /tmp/n2n/scripts/

# 解压，选择最大的edge文件
RUN /tmp/n2n/scripts/extract_n2n.sh
RUN /tmp/n2n/scripts/sel_n2n.sh

FROM alpine:3.8

ARG name="n2n"
ARG summary="n2n built on-top of alpine"
LABEL description="${summary}" \
  maintainer="<zctmdc@outlook.com>" \
  app.kubernetes.io/name="${name}" \
  org.opencontainers.image.title="${name}" \
  org.opencontainers.artifact.description="${summary}" \
  org.opencontainers.image.url="https://hub.docker.com/r/zctmdc/n2n" \
  org.opencontainers.image.source="https://github.com/zctmdc/docker/tree/alpha/n2n" \
  org.opencontainers.image.authors="zctmdc@outlook.com" \
  org.opencontainers.image.description="${summary}" \
  org.opencontainers.image.licenses="MIT"

RUN apk add --no-cache --upgrade bash iptables dhcp dhclient
RUN touch /var/lib/dhcp/dhcpd.leases

WORKDIR /usr/local/sbin/
COPY --from=downloader \
  /tmp/desc/supernode \
  /tmp/desc/edge \
  /usr/local/sbin/
RUN ls

WORKDIR /tmp/n2n/scripts/
COPY ./scripts/*.sh /tmp/n2n/scripts/
RUN chmod +x /tmp/n2n/scripts/*
RUN /tmp/n2n/scripts/fixlib.sh
RUN rm -rf /tmp/*

WORKDIR /usr/local/sbin/

ARG VERSION_B_S_rC
ENV VERSION_B_S_rC=${VERSION_B_S_rC}
