version: "3"
volumes:
    conf-frp:
networks:
    frp:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.37.83.0/24

services:

    frps-test:
        # build:
        #   context: .
        #   dockerfile: Dockerfile
        image: zctmdc/frp:alpha
        container_name: frps-test
        hostname: frp.example.org
        environment:
            - SUBDOMAIN_HOST=frp.example.org
            - MODE=RUN_FRPS
        networks:
            frp:
                ipv4_address: 10.37.83.10
        extra_hosts:
            - frp.example.org:10.37.83.10

    frpc-test-s:
        image: zctmdc/frp:alpha
        container_name: frpc-test-s
        hostname: frpc-test-s
        environment:
            - SUBDOMAIN_HOST=frp.example.org
            - MODE=RUN_FRPC
        depends_on:
            - frps-test
        networks:
            frp:
                ipv4_address: 10.37.83.20
        extra_hosts:
            - frp.example.org:10.37.83.10

    frpc-test-c:
        image: zctmdc/frp:Alpha
        container_name: frpc-test-c
        hostname: frp-test
        environment:
            - SUBDOMAIN_HOST=frps-test
        command: [ "RUN_FRPC" ]
        depends_on:
            - frps-test
            - frpc-test-s
        networks:
            frp:
                ipv4_address: 10.37.83.21
        extra_hosts:
            - frp.example.org:10.37.83.10