version: "3"
volumes:
  conf-frp:
services:
  zctmdc-frps:
    build:
      context: .
      dockerfile: Dockerfile
    image: zctmdc/frp:Alpha
    container_name: zctmdc-frps
    # network_mode: host
    restart: always
    environment:
      - SUBDOMAIN_HOST=frp.zctmdc.cc
      - VHOST_HTTP_PORT=3080
      - VHOST_HTTPS_PORT=3443
    ports:
      - 7000:7000/tcp
      - 7000:7000/udp
      - 7001:7001/udp
      - 7400:7400
      - 3080:3080
      - 3443:3443
    # volumes:
    #   - /path/to/conf:/etc/frp/:ro
    command: ["/usr/sbin/frps", "-c", "/etc/frp/frps.ini"]
    # healthcheck:
    #   test:
    #     [
    #       "CMD",
    #       "sh",
    #       "-c",
    #       "http_code=$$(curl -u $$ADMIN_USER:$$ADMIN_PWD -H -I -m 2 -o /dev/null -s -w %{http_code} http://$$SUBDOMAIN_HOST:$$ADMIN_PORT/api/serverinfo) && \
    #       if [[ $$http_code != 200 ]]; then \
    #         echo [ FRPS Dashboard check faild ]; \
    #         exit 11; \
    #       else \
    #         echo [ FRPS Dashboard check pass ]; \
    #       fi",
    #       "||",
    #       "exit 11",
    #     ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  zctmdc-frpc:
    image: zctmdc/frp:Alpha
    # hostname: your-name
    container_name: zctmdc-frpc
    # network_mode: host
    restart: always
    command: ["/usr/sbin/frpc", "-c", "/etc/frp/frpc.ini"]
    environment:
      - SUBDOMAIN_HOST=frp.zctmdc.cc
    # volumes:
    #   - conf-frp:/etc/frp/
    healthcheck:
      test: [
          "CMD",
          "bash",
          "-f",
          "/opt/healthcheck/healthcheck-frpc.sh",
          "||",
          # "sh", "-c",
          # "http_code=$$(curl -u $$ADMIN_USER:$$ADMIN_PWD -H -I -m 2 -o /dev/null -s -w %{http_code} http://$$(hostname -s).$$SUBDOMAIN_HOST:$$VHOST_HTTP_PORT/api/status) && \
          # if [[ $$http_code != 200 ]]; then \
          #   echo [ FRPC adminUI check faild ]; \
          #   exit 11; \
          # else \
          #   echo [ FRPC adminUI check pass ]; \
          # fi",
          "exit 11",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    # depends_on:
    #   - zctmdc-frps
