version: "3"
volumes:
  conf-frp:
services:
  frps-test:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: zctmdc/frp:Alpha
    container_name: frps-test
    hostname: frps-test
    environment:
      - SUBDOMAIN_HOST=frps-test
    # command: [ "/usr/sbin/frps", "-c", "/etc/frp/frps.ini"]
    command: [
        "/bin/bash",
        "-c",
        "/usr/sbin/frps -c /etc/frp/frps.ini \
        & sleep 5 \
        && /opt/healthcheck/healthcheck.sh",
      ]
  frpc-test:
    image: zctmdc/frp:Alpha
    container_name: frpc-test
    hostname: frpc-test
    environment:
      - SUBDOMAIN_HOST=frpc-test
    command: [ "/usr/sbin/frpc", "-c", "/etc/frp/frpc.ini"]
    depends_on:
      - frps-test
    links:
      - frps-test
      - frps-test:frpc-test.frps-test

  frp-test:
    image: zctmdc/frp:Alpha
    container_name: frp-test
    hostname: frp-test
    environment:
      - SUBDOMAIN_HOST=frps-test
    # command: [
    #     "/bin/bash",
    #     "-c",
    #     "/usr/sbin/frpc -c /etc/frp/frpc.ini \
    #     & sleep 5 \
    #     && /opt/healthcheck/healthcheck.sh",
    #   ]
    command: [ "/usr/sbin/frpc", "-c", "/etc/frp/frpc.ini"]
    depends_on:
      - frps-test
    links:
      - frps-test
      - frps-test:frp-test.frps-test