version: "3"
volumes:
    conf-frp:
networks:
    frp:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.37.83.0/24

services:

    frps-test:
        # build:
        #   context: .
        #   dockerfile: Dockerfile
        image: zctmdc/frp:alpha
        container_name: frps-test
        hostname: frp.example.org
        environment:
            - MODE=RUN_FRPS
            - SUBDOMAIN_HOST=frp.example.org
            - BIND_PORT=7000
            - BIND_UDP_PORT=7001
            - VHOST_HTTP_PORT=3080
            - VHOST_HTTPS_PORT=3443
            - ADMIN_USER=admin
            - ADMIN_PWD=admin
            - ADMIN_PORT=7400
        ports:
            - 7000:7000/tcp
            - 7000:7000/udp
            - 7001:7001/udp
            - 7400:7400
            - 3080:3080
            - 3443:3443
        networks:
            frp:
                ipv4_address: 10.37.83.10
        extra_hosts:
            - frp.example.org:10.37.83.10

    frpc-test-s:
        image: zctmdc/frp:alpha
        container_name: frpc-test-s
        depends_on:
            - frps-test
        hostname: frpc-test-s
        environment:
            - MODE=RUN_FRPC
            - SUBDOMAIN_HOST=frp.example.org
            - BIND_PORT=7000
            - BIND_UDP_PORT=7001
            - TOKEN=12345678
            - VHOST_HTTP_PORT=3080
            - ADMIN_USER=admin
            - ADMIN_PWD=admin
            - ADMIN_PORT=7400
            - SK=12345678
        ports:
            - 7500:7400
        networks:
            frp:
        extra_hosts:
            - frp.example.org:10.37.83.10

    frpc-test-c:
        image: zctmdc/frp:Alpha
        container_name: frpc-test-c
        depends_on:
            - frps-test
            - frpc-test-s
        hostname: frp-test
        environment:
            - SUBDOMAIN_HOST=frp.example.org
            - ADMIN_PORT=7501

        command: [ "RUN_FRPC" ]
        ports:
            - 7501:7501
        networks:
            frp:
        extra_hosts:
            - frp.example.org:10.37.83.10
