version: "3"
volumes:
  conf-frp:
services:
  frps-test:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: zctmdc/frp:Alpha
    container_name: frps-test
    hostname: frps-test
    environment:
      - SUBDOMAIN_HOST=frps-test
    command: ["/bin/bash", "-c", "/usr/sbin/frps -c /etc/frp/frps.ini"]

  frpc-test:
    image: zctmdc/frp:Alpha
    container_name: frpc-test
    # hostname: frpc-test
    environment:
      - SUBDOMAIN_HOST=frps-test
    command: [
        "/bin/bash",
        "-c",
        "/usr/sbin/frpc -c /etc/frp/frpc.ini \
        & sleep 2 \
        && /opt/healthcheck/healthcheck.sh",
        # # not working
        # "& url -k -m 1 --retry-connrefused --retry 5--retry-delay 1 \
        # http://localhost:${ADMIN_PORT}/api/status \
        # && /opt/healthcheck/healthcheck.sh",
      ]
    depends_on:
      - frps-test
    external_links:
      - frps-test
