version: "3"
volumes:
  conf-frp:
services:
  frps:
    build:
      context: .
      dockerfile: Dockerfile
    image: zctmdc/frp:Alpha
    restart: always
    network_mode: host
    # volumes:
    #   - /path/to/conf:/etc/frp/:ro
    command: ["/usr/sbin/frps", "-c", "/etc/frp/frps.ini"]
    healthcheck:
      test:
        [
          "CMD",
          "if [[ `curl -u admin:admin -H -I -m 2 -o /dev/null -s -w %{http_code} http://localhost:7400/api/serverinfo` != 200 ]]; then exit 1; else exit 0; fi",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  frpc:
    image: zctmdc/frp:Alpha
    restart: always
    network_mode: host
    command: ["/usr/sbin/frpc", "-c", "/etc/frp/frpc.ini"]
    # volumes:
    #   - conf-frp:/etc/frp/
    healthcheck:
      test:
        [
          "CMD",
          "if [[ `curl -u admin:admin -H -I -m 2 -o /dev/null -s -w %{http_code} http://localhost:7500/api/serverinfo` != 200 ]]; then exit 1 ; else exit 0; fi ",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
