version: "3"
volumes:
  conf-frp:
services:
  frps-demo:
    build:
      context: .
      dockerfile: Dockerfile
    image: zctmdc/frp:Alpha
    container_name: frps-demo
    hostname: frps-demo
    # network_mode: host
    restart: always
    environment:
      - SUBDOMAIN_HOST=frps-demo
      - BIND_PORT=7000
      - BIND_UDP_PORT=7001
      - VHOST_HTTP_PORT=3080
      - VHOST_HTTPS_PORT=3443
      - ADMIN_USER=admin
      - ADMIN_PWD=admin
      - ADMIN_PORT=7400
    ports:
      - 7000:7000/tcp
      - 7000:7000/udp
      - 7001:7001/udp
      - 7400:7400
      - 3080:3080
      - 3443:3443
    # volumes:
    #   - /path/to/conf:/etc/frp/:ro
    command: ["/usr/sbin/frps", "-c", "/etc/frp/frps.ini"]
    healthcheck:
      test: [
          "CMD",
          "/bin/bash",
          "-f",
          "/opt/healthcheck/healthcheck-frps.sh",
          "||",
    #       "/bin/bash",
    #       "-c",
    #       "http_code=$$(curl -u $$ADMIN_USER:$$ADMIN_PWD -H -I -m 2 -o /dev/null -s -w %{http_code} --connect-timeout 10 http://$$SUBDOMAIN_HOST:$$ADMIN_PORT/api/serverinfo) && \
    #       if [[ $$http_code != 200 ]]; then \
    #         echo [ FRPS Dashboard check faild ]; \
    #         exit 1; \
    #       else \
    #         echo [ FRPS Dashboard check pass ]; \
    #       fi",
    #       "||",
          "exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  frpc-demo:
    image: zctmdc/frp:Alpha
    # hostname: frpc-demo
    container_name: frpc-demo
    # network_mode: host
    restart: always
    environment:
      - SUBDOMAIN_HOST=frps-demo
      - BIND_PORT=7000
      - BIND_UDP_PORT=7001
      - TOKEN=12345678
      - VHOST_HTTP_PORT=3080
      - ADMIN_USER=admin
      - ADMIN_PWD=admin
      - ADMIN_PORT=7400
      - SK=12345678
    # volumes:
    #   - conf-frp:/etc/frp/
    command: ["/usr/sbin/frpc", "-c", "/etc/frp/frpc.ini"]
    healthcheck:
      test: [
          "CMD",
          "/bin/bash",
          "-f",
          "/opt/healthcheck/healthcheck-frpc.sh",
          "||",
          # "/bin/bash", "-c",
          # "http_code=$$(curl -u $$ADMIN_USER:$$ADMIN_PWD -H -I -m 2 -o /dev/null -s -w %{http_code} --connect-timeout 10 http://$$(hostname -s).$$SUBDOMAIN_HOST:$$VHOST_HTTP_PORT/api/status) && \
          # if [[ $$http_code != 200 ]]; then \
          #   echo [ FRPC adminUI check faild ]; \
          #   exit 1; \
          # else \
          #   echo [ FRPC adminUI check pass ]; \
          # fi",
          "exit",
          "11",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - frps-demo
    external_links:
      - frps-demo