version: "3"
services:
  n2n_supernode:
    build:
      context: .
      dockerfile: Dockerfile
    image: zctmdc/n2n_ntop:Alpha
    restart: always
    privileged: true
    ports:
      - 10086:10086/udp
    environment:
      - MODE=SUPERNODE
      - SUPERNODE_PORT=10086
      - N2N_ARGS=-v -f

  n2n_proxy_dhcpd:
    image: zctmdc/n2n_proxy:Alpha
    restart: always
    privileged: true
    environment:
      - MODE=DHCPD
      - SUPERNODE_HOST=n2n_supernode
      - SUPERNODE_PORT=10086
      - EDGE_TUN=edge_proxy_dhcpd
      - EDGE_IP=10.10.10.1
      - EDGE_COMMUNITY=n2n
      - EDGE_KEY=test
      - EDGE_ENCRYPTION=A3
      - N2N_ARGS=-f
      - EDGE_NAT=TRUE
      - EDGE_PROXY=TRUE
      - PROXY_ARGS=-L=:14080
    # volumes:
    #   - ./dhcpd.conf:/etc/dhcp/dhcpd.conf:ro
    external_links:
      - n2n_supernode:n2n_supernode
    depends_on:
      - n2n_supernode

  n2n_proxy_dhcp:

    image: zctmdc/n2n_proxy:Alpha
    restart: always
    privileged: true
    environment:
      - MODE=DHCP
      - SUPERNODE_HOST=n2n_supernode
      - SUPERNODE_PORT=10086
      - EDGE_TUN=edge_proxy_dhcp
      - EDGE_COMMUNITY=n2n
      - EDGE_KEY=test
      - EDGE_ENCRYPTION=A3
      - N2N_ARGS=-f
      - EDGE_ROUTE=TRUE
      - EDGE_PROXY=FALSE
      - EDGE_DESTINATION=192.168.0.0/16
      - EDGE_GATEWAY=10.10.10.10
    external_links:
      - n2n_supernode:n2n_supernode
    depends_on:
      - n2n_supernode
      - n2n_proxy_dhcpd

  n2n_proxy_static:
    image: zctmdc/n2n_proxy:Alpha
    restart: always
    privileged: true
    environment:
      - MODE=STATIC
      - SUPERNODE_HOST=n2n_supernode
      - SUPERNODE_PORT=10086
      - EDGE_TUN=edge_proxy_static
      - EDGE_IP=10.10.10.10
      - EDGE_COMMUNITY=n2n
      - EDGE_KEY=test
      - EDGE_ENCRYPTION=A3
      - N2N_ARGS=-f
      - EDGE_PROXY=TRUE
      - PROXY_ARGS=-L=:14080 -F=10.10.10.1:14080
    ports:
      - 14080:14080
    external_links:
      - n2n_supernode:n2n_supernode
    depends_on:
      - n2n_supernode