name: frp

on:
    push:
        branches:
            - alpha
    pull_request:
        branches:
            - alpha

env:
    USERNAME: zctmdc
    TAGNAME: Alpha

jobs:
    frp:
        if: ${{false}}
        runs-on: ubuntu-latest
        env:
            APPNAME: frp
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: ${{ env.APPNAME }}
                  platforms: linux/amd64,linux/arm64,linux/arm/v7
                  push: true
                  tags: ${{ env.USERNAME }}/${{ env.APPNAME }}:${{ env.TAGNAME }}
                  cache-from: type=registry,ref=${{ env.USERNAME }}/${{ env.APPNAME }}:buildcache-${{ env.TAGNAME }}
                  cache-to: type=registry,ref=${{ env.USERNAME }}/${{ env.APPNAME }}:buildcache-${{ env.TAGNAME }},mode=max

            - name: Test Docker
              run: |
                  if [[ -f ${{ env.APPNAME }}/docker-compose.test.yaml ]]; then
                    docker-compose -f ./${{ env.APPNAME }}/docker-compose.test.yaml up --exit-code-from  ${{ env.APPNAME }}-test || exit 1
                  fi
