name: build zctmdc/n2n_proxy:Alpha

on:
  push:
    branches:
      - alpha
  pull_request:
    branches:
      - alpha

env:
  USERNAME: zctmdc
  APPNAME: n2n_proxy
  TAGNAME: Alpha

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.APPNAME }}
          push: true
          tags: ${{ env.USERNAME }}/${{ env.APPNAME }}:${{ env.TAGNAME }}
          cache-from: type=registry,ref=${{ env.USERNAME }}/${{ env.APPNAME }}:${{ env.TAGNAME }}buildcache
          cache-to: type=registry,ref=${{ env.USERNAME }}/${{ env.APPNAME }}:${{ env.TAGNAME }}buildcache,mode=max
