name: n2n-build-all-pre

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
    workflow_call:
        inputs:
            VERSION_BIG:
                description: "version_big                 e.g. v3 | v2"
                required: true
                type: string
            VERSION_SMALL:
                description: "version_small               e.g. 3.1.1 | 2.1.0"
                required: false
                type: string
            VERSION_COMMIT:
                description: "version_commit              e.g. 1255 | 124"
                required: false
                type: string
            VERSION_B_S_rC:
                description: "version_b_s_rc              e.g. v3 | v3_3.1.1_r1255"
                required: true
                type: string
            STR_OS_ARCHS:
                description: "str_os_archs                e.g. linux/amd64"
                required: true
                type: string
            STR_DOWNLOAD_URLS:
                description: "str_download_urls           e.g. https://raw.githubusercontent.com/lucktu/n2n/master/Linux/n2n_v3_linux_x64_v3.1.1_r1255_static_by_heiye.tar.gz"
                required: true
                type: string
            FORCE_PUSH:
                description: "force push to registry"
                required: true
                type: boolean
                default: false
            NEED_FIXLIB_VERSIONS_B_S_rC:
                description: "ned fixlib versions_b_s_rc"
                required: true
                type: string
                default: "v2_2.3.0, v2s_2.1.0_r111, v1"
            DEFIN_LATEST_VERSION:
                description: "defin_latest_version        e.g. v3 | v4"
                default: "v3"
                required: true
                type: string
            DOCKER_BUILD_DOCKERFILE_OK:
                description: "docker_build_dockerfile_ok  e.g. Dockerfile.build.ubuntu-20.04 | Dockerfile.build.alpine-latest | Dockerfile.build.debian-stable"
                default: "Dockerfile.build.debian-stable"
                required: true
                type: string
            DOCKER_BUILD_DOCKERFILE_FIX:
                description: "docker_build_dockerfile_fix e.g. Dockerfile.build.ubuntu-18.04 | Dockerfile.build.alpine-3.8 | Dockerfile.build.debian-stable"
                default: "Dockerfile.build.debian-stable"
                required: true
                type: string
            DOCKER_BUILD_WHITH_OUT_CACHE:
                default: false
                description: "docker_build_whith_out_cache"
                required: true
                type: boolean
                
env:
    DOCKER_CONTEXT_PATH: n2n
    DOCKER_APP_NAME: n2n

jobs:
    TAG-BUILD-docker-n2n-build-test:
        name: TAG-BUILD-docker-n2n-build-test
        permissions:
            contents: read
            packages: write
            # This is used to complete the identity challenge
            # with sigstore/fulcio when running outside of PRs.
            id-token: write
        uses: ./.github/workflows/n2n_01x00_call-build-all.yml
        secrets: inherit
        with:
            VERSION_BIG: ${{ inputs.VERSION_BIG }}
            VERSION_SMALL: ${{ inputs.VERSION_SMALL }}
            VERSION_COMMIT: ${{ inputs.VERSION_COMMIT }}
            VERSION_B_S_rC: ${{ inputs.VERSION_B_S_rC }}
            STR_OS_ARCHS: ${{ inputs.STR_OS_ARCHS }}
            STR_DOWNLOAD_URLS: ${{ inputs.STR_DOWNLOAD_URLS }}
            DOCKER_BUILD_PLATFORMS: ${{ inputs.STR_OS_ARCHS }}
            NEED_FIXLIB_VERSIONS_B_S_rC: ${{ inputs.NEED_FIXLIB_VERSIONS_B_S_rC }}
            FORCE_PUSH: ${{ inputs.FORCE_PUSH }}
            DOCKER_CONTEXT_PATH: "n2n"
            DOCKER_APP_NAME: "n2n"
            DOCKER_TAG_PREFIX: "build-"
            DEFIN_LATEST_VERSION: ${{ inputs.DEFIN_LATEST_VERSION }}
            DOCKER_BUILD_DOCKERFILE_OK: ${{ inputs.DOCKER_BUILD_DOCKERFILE_OK }}
            DOCKER_BUILD_DOCKERFILE_FIX: ${{ inputs.DOCKER_BUILD_DOCKERFILE_FIX }}
            DOCKER_TEST_SCRIPTS_PATH: "n2n/scripts/build"
            DOCKER_BUILD_WHITH_OUT_CACHE: ${{ inputs.DOCKER_BUILD_WHITH_OUT_CACHE }}

    TAG-RUN-docker-n2n-build-test:
        name: TAG-RUN-docker-n2n-build-test
        needs: ["TAG-BUILD-docker-n2n-build-test"]
        permissions:
            contents: read
            packages: write
            # This is used to complete the identity challenge
            # with sigstore/fulcio when running outside of PRs.
            id-token: write
        uses: ./.github/workflows/n2n_01x00_call-build-all.yml
        secrets: inherit
        with:
            VERSION_BIG: ${{ inputs.VERSION_BIG }}
            VERSION_SMALL: ${{ inputs.VERSION_SMALL }}
            VERSION_COMMIT: ${{ inputs.VERSION_COMMIT }}
            VERSION_B_S_rC: ${{ inputs.VERSION_B_S_rC }}
            STR_OS_ARCHS: ${{ inputs.STR_OS_ARCHS }}
            STR_DOWNLOAD_URLS: ${{ inputs.STR_DOWNLOAD_URLS }}
            DOCKER_BUILD_PLATFORMS: ${{ inputs.STR_OS_ARCHS }}
            FORCE_PUSH: ${{ inputs.FORCE_PUSH }}
            DOCKER_CONTEXT_PATH: "n2n"
            DOCKER_APP_NAME: "n2n"
            DOCKER_BUILD_DOCKERFILE: "Dockerfile.run"
            DEFIN_LATEST_VERSION: ${{ inputs.DEFIN_LATEST_VERSION }}
            DOCKER_BUILD_DOCKERFILE_OK: ${{ inputs.DOCKER_BUILD_DOCKERFILE_OK }}
            DOCKER_BUILD_DOCKERFILE_FIX: ${{ inputs.DOCKER_BUILD_DOCKERFILE_FIX }}
            DOCKER_TEST_SCRIPTS_PATH: "n2n/scripts/run"
            DOCKER_BUILD_WHITH_OUT_CACHE: ${{ inputs.DOCKER_BUILD_WHITH_OUT_CACHE }}
