name: n2n-init-version

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
    workflow_call:
        inputs:
            VERSION_BIG:
                description: "version_big               e.g. v3 | v2"
                required: true
                type: string
            VERSION_SMALL:
                description: "version_small             e.g. 3.1.1 | 2.1.0"
                required: false
                type: string
            VERSION_COMMIT:
                description: "version_commit            e.g. 1255 | 124"
                required: false
                type: string
            VERSION_B_S_rC:
                description: "version_b_s_rc            e.g. v3 | v3_3.1.1_r1255"
                required: true
                type: string
            STR_OS_ARCHS:
                description: "str_os_archs              e.g. linux/amd64"
                required: true
                type: string
            STR_DOWNLOAD_URLS:
                description: "str_download_urls         e.g. https://raw.githubusercontent.com/lucktu/n2n/master/Linux/n2n_v3_linux_x64_v3.1.1_r1255_static_by_heiye.tar.gz"
                required: true
                type: string
            FORCE_PUSH:
                description: "force push to registry"
                default: false
                required: false
                type: boolean
            NEED_FIXLIB_VERSIONS_B_S_rC:
                description: "ned fixlib versions_b_s_rc"
                required: true
                type: string
                default: "v2_2.3.0, v2s_2.1.0_r111, v1"
            DOCKER_BUILD_DOCKERFILE:
                description: "docker_build_dockerfile     e.g. Dockerfile.run"
                required: false
                type: string
            DEFIN_LATEST_VERSION:
                description: "defin_latest_version        e.g. v3 | v4"
                default: "v3"
                required: true
                type: string
            DOCKER_BUILD_DOCKERFILE_FIX:
                description: "docker_build_dockerfile_fix e.g. Dockerfile.build.ubuntu-18.04 | Dockerfile.build.alpine-3.8 | Dockerfile.build.debian-stable"
                default: "Dockerfile.build.debian-stable"
                required: true
                type: string
            DOCKER_BUILD_DOCKERFILE_OK:
                description: "docker_build_dockerfile_ok  e.g. Dockerfile.build.ubuntu-20.04 | Dockerfile.build.alpine-latest | Dockerfile.build.debian-stable"
                default: "Dockerfile.build.debian-stable"
                required: true
                type: string

        outputs:
            ONLY_BIGVERSION:
                description: "docker build only bigversion"
                value: ${{ jobs.init-version.outputs.ONLY_BIGVERSION }}
            IS_LATEST_VERSION:
                description: "docker build is latest version"
                value: ${{ jobs.init-version.outputs.IS_LATEST_VERSION }}
            NEED_FIX:
                description: "docker build need fix"
                value: ${{ jobs.init-version.outputs.NEED_FIX }}
            DOCKER_BUILD_DOCKERFILE:
                description: "docker build dockerfile"
                value: ${{ jobs.init-version.outputs.DOCKER_BUILD_DOCKERFILE }}
            DOCKER_BUILD_CACHE_TAG:
                description: "docker build-cache tag"
                value: ${{ jobs.init-version.outputs.DOCKER_BUILD_CACHE_TAG }}

jobs:
    init-version:
        name: ${{ inputs.VERSION_B_S_rC }} - init-version
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            # This is used to complete the identity challenge
            # with sigstore/fulcio when running outside of PRs.
            id-token: write
        outputs:
            ONLY_BIGVERSION: ${{ steps.check-big-version-only.outputs.ONLY_BIGVERSION }}
            IS_LATEST_VERSION: ${{ steps.check-latest-version.outputs.IS_LATEST_VERSION }}
            NEED_FIX: ${{ steps.check-need-fix.outputs.NEED_FIX }}
            DOCKER_BUILD_DOCKERFILE: ${{ steps.check-need-fix.outputs.DOCKER_BUILD_DOCKERFILE }}
            DOCKER_BUILD_CACHE_TAG: ${{ steps.init-build-cache-tag.outputs.DOCKER_BUILD_CACHE_TAG }}

        steps:
            - name: ${{ inputs.VERSION_B_S_rC }} - Check inputs
              run: |
                  LOG_INFO() {
                    echo -e $(caller) "\033[0;32m[    INFO] $@ \033[0m"
                  }
                  LOG_INFO "VERSION_BIG: ${{ inputs.VERSION_BIG }}"
                  LOG_INFO "VERSION_SMALL: ${{ inputs.VERSION_SMALL }}"
                  LOG_INFO "VERSION_COMMIT: ${{ inputs.VERSION_COMMIT }}"
                  LOG_INFO "VERSION_B_S_rC: ${{ inputs.VERSION_B_S_rC }}"
                  LOG_INFO "STR_OS_ARCHS: ${{ inputs.STR_OS_ARCHS }}"
                  LOG_INFO "STR_DOWNLOAD_URLS: ${{ inputs.STR_DOWNLOAD_URLS }}"
                  LOG_INFO "FORCE_PUSH: ${{ inputs.FORCE_PUSH }}"

            - name: ${{ inputs.VERSION_B_S_rC }} - Check big version only
              id: check-big-version-only
              run: |
                  LOG_INFO() {
                    echo -e $(caller) "\033[0;32m[    INFO] $@ \033[0m"
                  }
                  if [[ '${{ inputs.VERSION_B_S_rC }}' == '${{ inputs.VERSION_BIG }}' ]]; then
                    only_bigversion=true
                  else
                    only_bigversion=false
                  fi
                  LOG_INFO "ONLY_BIGVERSION=${only_bigversion}"
                  echo "ONLY_BIGVERSION=${only_bigversion}" >> $GITHUB_OUTPUT

            - name: ${{ inputs.VERSION_B_S_rC }} - Check latest version
              id: check-latest-version
              run: |
                  LOG_INFO() {
                    echo -e $(caller) "\033[0;32m[    INFO] $@ \033[0m"
                  }
                  if [[ '${{ inputs.VERSION_B_S_rC }}' == '${{ inputs.DEFIN_LATEST_VERSION }}' ]]; then
                    is_latest_version=true
                  else
                    is_latest_version=false
                  fi
                  LOG_INFO "IS_LATEST_VERSION=${is_latest_version}"
                  echo "IS_LATEST_VERSION=${is_latest_version}" >> $GITHUB_OUTPUT

            - name: ${{ inputs.VERSION_B_S_rC }} - Check need fix
              id: check-need-fix
              run: |
                  LOG_INFO() {
                    echo -e $(caller) "\033[0;32m[    INFO] $@ \033[0m"
                  }
                  LOG_WARNING() {
                    echo -e $(caller) "\033[0;33m[ WARNING] $@ \033[0m"
                  }
                  ned_libfix_versions_b_s_rc="${{ inputs.NEED_FIXLIB_VERSIONS_B_S_rC }}"
                  l_ned_libfix_versions_b_s_rc=(${ned_libfix_versions_b_s_rc//,/ })
                  for ned_libfix_versions_b_s_rc in ${l_ned_libfix_versions_b_s_rc[@]};do
                    if [[ "${{ inputs.version_b_s_rc }}" == "${ned_libfix_versions_b_s_rc}" ]]; then
                      LOG_WARNING 需要修复 - ${BUILD_VERSION_B_S_rC}
                      echo "NEED_FIX=true">> $GITHUB_OUTPUT
                      if [[ -n "${{ inputs.DOCKER_BUILD_DOCKERFILE }}" ]]; then
                        build_dockerfile=${{ inputs.DOCKER_BUILD_DOCKERFILE }}
                      else
                        build_dockerfile=${{ inputs.DOCKER_BUILD_DOCKERFILE_FIX }}
                      fi
                      LOG_INFO 使用 ${build_dockerfile} - ${build_dockerfile}
                      echo "DOCKER_BUILD_DOCKERFILE=${build_dockerfile}">> $GITHUB_OUTPUT
                      exit 0
                    fi
                  done
                  echo "NEED_FIX=false">> $GITHUB_OUTPUT
                  if [[ -n "${{ inputs.DOCKER_BUILD_DOCKERFILE }}" ]]; then
                    build_dockerfile=${{ inputs.DOCKER_BUILD_DOCKERFILE }}
                  else
                    build_dockerfile=${{ inputs.DOCKER_BUILD_DOCKERFILE_OK }}
                  fi
                  LOG_INFO 使用 ${build_dockerfile} - ${build_dockerfile}
                  echo "DOCKER_BUILD_DOCKERFILE=${build_dockerfile}">> $GITHUB_OUTPUT

            - name: ${{ inputs.VERSION_B_S_rC }} - Init build cache tag
              id: init-build-cache-tag
              run: |
                  LOG_INFO() {
                    echo -e $(caller) "\033[0;32m[    INFO] $@ \033[0m"
                  }
                  if [[ -n "${{ inputs.DOCKER_BUILD_DOCKERFILE }}" ]]; then
                    docker_build_cache_tag="build-cache-${{ inputs.DOCKER_BUILD_DOCKERFILE }}"
                  elif [[ "${{ steps.check-need-fix.outputs.NEED_FIX }}" == "true" ]]; then
                    docker_build_cache_tag="build-cache-fix"
                  else
                    docker_build_cache_tag="build-cache"
                  fi
                  LOG_INFO "DOCKER_BUILD_CACHE_TAG: ${docker_build_cache_tag}"
                  echo "DOCKER_BUILD_CACHE_TAG=${docker_build_cache_tag}" >> $GITHUB_OUTPUT
