name: manual-scan-all-to-build-n2n

on:
  workflow_dispatch:
    inputs:
      build-releases-version:
        description: "Build all releases versions? v3|v2s|v2|v1"
        required: true
        type: boolean
        default: false
      force-push:
        description: "force push to registry"
        required: true
        type: boolean
        default: false

jobs:
  echo-input:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - run:
          echo "force-push - ${{ inputs.force-push }}"
          echo "build-releases-versio - ${{ inputs.build-releases-versio }}"

  build-all-releases-version:
    permissions:
      contents: read
      packages: write
      id-token: write
    if: ${{ inputs.build-releases-version }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        version_b_s_rc: [v1, v2, v2s, v3]

    uses: ./.github/workflows/docker-publish-n2n.yml
    with:
      version_b_s_rc: ${{ matrix.version_b_s_rc }}
      force_push: ${{ inputs.force-push }}
    secrets: inherit
